name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    -
      name: Build the Docker image
      working-directory: ./fermentrack
      run: |
        docker buildx build \
        --platform=linux/arm/v7,linux/amd64 \
        --output "type=image" \
        --file Dockerfile . \
        --tag my-image-name:$(date +%s)
